FROM golang:1.26-alpine
RUN apk add --no-cache git ca-certificates libc6-compat

# Устанавливаем Delve
RUN go install github.com/go-delve/delve/cmd/dlv@latest

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Собираем бинарник для дебага
RUN go build -gcflags="all=-N -l" -o main ./main.go

# Используем переменную DLV_PORT
CMD /go/bin/dlv --listen=:${DLV_PORT} --headless=true --api-version=2 --accept-multiclient exec ./main
